# /usr/src/libc/time/Makefile 8/3/94

LIBOBJ=\
	$(TARGET)(clock.o) \
	$(TARGET)(ctime.o) \
	$(TARGET)(difftime.o) \
	$(TARGET)(mktime.o) \
	$(TARGET)(strftime.o)

# Primary target.
all:	$(LIBOBJ)
	: libc/time done.

# end of /usr/src/libc/time/Makefile
