# /usr/src/libc/stdlib/malloc/Makefile 6/8/94

LIBOBJ=\
	$(TARGET)(calloc.o) \
	$(TARGET)(malloc.o) \
	$(TARGET)(memok.o) \
	$(TARGET)(notmem.o) \
	$(TARGET)(realloc.o)

UNUSED=trymallo.c

# Primary target.
all:	$(LIBOBJ)
	: libc/stdlib/malloc done

# end of /usr/src/libc/stdlib/malloc/Makefile
