# /usr/src/libc/stdio/i386/Makefile 6/8/94

LIBOBJ=\
	$(TARGET)(fgetw.o) \
	$(TARGET)(fputw.o) \
	$(TARGET)(getw.o) \
	$(TARGET)(putw.o)

# Primary target.
all:	$(LIBOBJ)
	: libc/stdio/i386 done.

# end of libc/stdio/i386/Makefile
