# /usr/src/libc/string/i386/Makefile 6/8/94

LIBOBJ=\
	$(TARGET)(_memxchg.o) \
	$(TARGET)(index.o) \
	$(TARGET)(memccpy.o) \
	$(TARGET)(memchr.o) \
	$(TARGET)(memcmp.o) \
	$(TARGET)(memcpy.o) \
	$(TARGET)(memmove.o) \
	$(TARGET)(memset.o) \
	$(TARGET)(rindex.o) \
	$(TARGET)(strcat.o) \
	$(TARGET)(strchr.o) \
	$(TARGET)(strcmp.o) \
	$(TARGET)(strcpy.o) \
	$(TARGET)(strcspn.o) \
	$(TARGET)(streq.o) \
	$(TARGET)(strlen.o) \
	$(TARGET)(strpbrk.o) \
	$(TARGET)(strrchr.o) \
	$(TARGET)(strspn.o) \
	$(TARGET)(strstr.o)

# Primary target.
all:	$(LIBOBJ)
	: libc/string/i386 done

# end of /usr/src/libc/string/i386/Makefile
