# /usr/src/libc/ctype/Makefile 6/8/94

LIBOBJ=\
	$(TARGET)(_ctype.o)\
	$(TARGET)(_tolower.o)\
	$(TARGET)(_toupper.o)\
	$(TARGET)(isalnum.o)\
	$(TARGET)(isalpha.o)\
	$(TARGET)(isascii.o)\
	$(TARGET)(iscntrl.o)\
	$(TARGET)(isdigit.o)\
	$(TARGET)(isgraph.o)\
	$(TARGET)(islower.o)\
	$(TARGET)(isprint.o)\
	$(TARGET)(ispunct.o)\
	$(TARGET)(isspace.o)\
	$(TARGET)(isupper.o)\
	$(TARGET)(isxdigit.o)\
	$(TARGET)(toascii.o)\
	$(TARGET)(tolower.o)\
	$(TARGET)(toupper.o)

# Primary target.
all:	$(LIBOBJ)
	: lib/ctype done

# end of /usr/src/libc/ctype/Makefile
